version: '3'
services:
  simple-transaction:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: simple-transaction
    ports:
      - 8000:80
    volumes:
      - ../:/var/www/app
    depends_on:
      - mysql
  mysql:
    image: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=transactions
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
volumes:
  mysql-volume:
